version: "3.1"
services:

# http://localhost:15672
#https://www.rabbitmq.com/getstarted.html
rabbitmq:
  image: "rabbitmq:3-management-alpine"
  environment:
    RABBITMQ_DEFAULT_USER: admin
    RABBITMQ_DEFAULT_PASS: beingzero
  ports:
  - "4369:4369"
  - "5672:5672"
  - "15672:15672"
  - "25672:25672"
  networks:
  - beingzero
networks:
- beingzero
